# Generated by Django 4.0.5 on 2022-06-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jeans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название джинс')),
                ('descriprion', models.TextField(max_length=5000, verbose_name='Описание')),
                ('price', models.CharField(max_length=50, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Джинсы',
                'verbose_name_plural': 'Джинсы',
            },
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название обуви')),
                ('descriprion', models.TextField(max_length=5000, verbose_name='Описание')),
                ('price', models.CharField(max_length=50, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Обувь',
                'verbose_name_plural': 'Обувь',
            },
        ),
        migrations.CreateModel(
            name='Sweatshirts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название кофты')),
                ('descriprion', models.TextField(max_length=5000, verbose_name='Описание')),
                ('price', models.CharField(max_length=50, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Кофта',
                'verbose_name_plural': 'Кофты',
            },
        ),
        migrations.CreateModel(
            name='Tshirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название футболки')),
                ('descriprion', models.TextField(max_length=5000, verbose_name='Описание')),
                ('price', models.CharField(max_length=50, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Футболка',
                'verbose_name_plural': 'Футболки',
            },
        ),
    ]
