# Generated by Django 4.0.5 on 2022-06-29 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/category/', verbose_name='Изображение')),
                ('imageswhite', models.ImageField(blank=True, null=True, upload_to='images/category/', verbose_name='Белое изображение')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000, verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Размер')),
            ],
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название обуви')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('descriprion', models.TextField(max_length=5000, verbose_name='Краткое описание товара')),
                ('descriprion_full', models.TextField(max_length=5000, verbose_name='Полное описание товара')),
                ('sex', models.CharField(choices=[('Мужские', 'Мужские кроссовки'), ('Женские', 'Женские кроссовки')], max_length=100)),
                ('price', models.CharField(max_length=60, verbose_name='Стоимость')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение в списке')),
                ('images2', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение 2')),
                ('images3', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение 3')),
                ('firm', models.CharField(choices=[('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Reebok', 'Reebok'), ('Puma', 'Puma'), ('New Balance', 'New Balance'), ('Asics', 'Asics'), ('Lacoste', 'Lacoste')], max_length=100)),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapi.category', verbose_name='Категория')),
                ('size', models.ManyToManyField(to='myapi.size')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
