# Generated by Django 4.0.5 on 2022-06-23 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jeans',
            options={'verbose_name': 'джинсы', 'verbose_name_plural': 'джинсы'},
        ),
        migrations.AlterModelOptions(
            name='shoes',
            options={'verbose_name': 'обувь', 'verbose_name_plural': 'обувь'},
        ),
        migrations.AlterModelOptions(
            name='sweatshirts',
            options={'verbose_name': 'кофту', 'verbose_name_plural': 'кофты'},
        ),
        migrations.AlterModelOptions(
            name='tshirt',
            options={'verbose_name': 'футболку', 'verbose_name_plural': 'футболки'},
        ),
    ]
