# Generated by Django 4.0.5 on 2022-06-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_jeans_options_alter_shoes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='size',
            field=models.CharField(choices=[('36', 'Размер 36'), ('37', 'Размер 37'), ('38', 'Размер 38'), ('39', 'Размер 39'), ('40', 'Размер 40'), ('41', 'Размер 41'), ('42', 'Размер 42'), ('43', 'Размер 43'), ('44', 'Размер 44')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoes',
            name='price',
            field=models.CharField(max_length=60, verbose_name='Стоимость'),
        ),
    ]
