# Generated by Django 4.0.5 on 2022-06-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_shoes_size_alter_shoes_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoes',
            name='size',
        ),
        migrations.AddField(
            model_name='shoes',
            name='size36',
            field=models.BooleanField(default=False, verbose_name='36 размер'),
        ),
        migrations.AddField(
            model_name='shoes',
            name='size37',
            field=models.BooleanField(default=False, verbose_name='37 размер'),
        ),
        migrations.AddField(
            model_name='shoes',
            name='size38',
            field=models.BooleanField(default=False, verbose_name='38 размер'),
        ),
        migrations.AddField(
            model_name='shoes',
            name='size39',
            field=models.BooleanField(default=False, verbose_name='39 размер'),
        ),
        migrations.AddField(
            model_name='shoes',
            name='size40',
            field=models.BooleanField(default=False, verbose_name='40 размер'),
        ),
        migrations.AddField(
            model_name='shoes',
            name='size41',
            field=models.BooleanField(default=False, verbose_name='41 размер'),
        ),
        migrations.AddField(
            model_name='shoes',
            name='size42',
            field=models.BooleanField(default=False, verbose_name='42 размер'),
        ),
        migrations.AddField(
            model_name='shoes',
            name='size43',
            field=models.BooleanField(default=False, verbose_name='43 размер'),
        ),
        migrations.AddField(
            model_name='shoes',
            name='size44',
            field=models.BooleanField(default=False, verbose_name='36 размер'),
        ),
    ]
