# Generated by Django 4.0.5 on 2022-06-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_remove_shoes_size_shoes_size36_shoes_size37_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='sex',
            field=models.CharField(choices=[('Мужские', 'Мужские'), ('Женские', 'Женские')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
