# Generated by Django 4.0.5 on 2022-06-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_shoes_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIZE_CHOICES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='size36',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='size37',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='size38',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='size39',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='size40',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='size41',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='size42',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='size43',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='size44',
        ),
        migrations.AddField(
            model_name='shoes',
            name='size',
            field=models.ManyToManyField(to='myapi.size_choices'),
        ),
    ]
