# Generated by Django 4.0.5 on 2022-06-24 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_size_choices_remove_shoes_size36_remove_shoes_size37_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size_choices',
            old_name='choice',
            new_name='name',
        ),
    ]
