# Generated by Django 4.0.5 on 2022-06-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_size_choices_choice_alter_size_choices_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size_choices',
            name='choice',
        ),
        migrations.AlterField(
            model_name='size_choices',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
