# Generated by Django 4.0.5 on 2022-06-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_remove_size_choices_choice_alter_size_choices_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='size_choices',
            name='namesize',
            field=models.CharField(default='', max_length=200, verbose_name='размер'),
            preserve_default=False,
        ),
    ]
