# Generated by Django 4.0.5 on 2022-06-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0012_remove_size_choices_namesize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='sex',
            field=models.CharField(choices=[('Мужские', 'Мужские кроссовки'), ('Женские', 'Женские кроссовки')], max_length=100),
        ),
    ]
