# Generated by Django 4.0.5 on 2022-06-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0015_alter_size_choices_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sizechoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название обуви')),
            ],
        ),
        migrations.DeleteModel(
            name='SIZE_CHOICES',
        ),
        migrations.AlterField(
            model_name='shoes',
            name='size',
            field=models.ManyToManyField(to='myapi.sizechoice'),
        ),
    ]
