# Generated by Django 4.0.5 on 2022-06-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0018_size_delete_size_choices_alter_shoes_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
