# Generated by Django 4.0.5 on 2022-06-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0020_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000, verbose_name='Текст')),
            ],
        ),
    ]
