# Generated by Django 4.0.5 on 2022-06-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0021_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.AddField(
            model_name='shoes',
            name='firm',
            field=models.CharField(choices=[('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Reebok', 'Reebok'), ('Puma', 'Puma'), ('New Balance', 'New Balance'), ('Asics', 'Asics'), ('Lacoste', 'Lacoste')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
