# Generated by Django 4.0.5 on 2022-06-28 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0023_alter_category_options_shoes_cat_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapi.category'),
        ),
    ]
