# Generated by Django 4.0.5 on 2022-06-28 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0024_alter_shoes_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoes',
            name='cat',
        ),
    ]
