# Generated by Django 4.0.5 on 2022-06-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0026_shoes_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/category/', verbose_name='Изображение'),
        ),
    ]
