# Generated by Django 4.0.5 on 2022-06-29 08:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0027_category_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/category/', validators=[django.core.validators.validate_image_file_extension], verbose_name='Изображение'),
        ),
    ]
