# Generated by Django 4.0.5 on 2022-06-29 08:05

from django.db import migrations, models
import myapi.validators


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0028_alter_category_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='file',
            field=models.FileField(default='', upload_to='images/category/', validators=[myapi.validators.validate_file_extension]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/category/', verbose_name='Изображение'),
        ),
    ]
