# Generated by Django 4.0.5 on 2022-06-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0029_category_file_alter_category_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='file',
        ),
        migrations.AddField(
            model_name='category',
            name='imageswhite',
            field=models.ImageField(blank=True, null=True, upload_to='images/category/', verbose_name='Белое изображение'),
        ),
    ]
